- name: Configure LAMP Stack
  hosts: all
  become: yes
  vars:
    php_version: "8.2"
    db_host: "{{ lookup('aws_ssm', '/prod/db/endpoint') }}"
    db_name: "appdb"

  roles:
    - role: lamp

  tasks:
    - name: Deploy application code
      copy:
        src: ../../app/src/
        dest: /var/www/html/
        owner: www-data
        group: www-data
      notify: Restart Apache
