- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Configure virtual host
  template:
    src: templates/vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache
