name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: ./infrastructure
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./infrastructure
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infrastructure
        run: terraform plan -out=tfplan.binary

      - name: Upload Terraform Plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infrastructure/tfplan.binary

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible-lint
        run: sudo pip install ansible-lint
      - name: Lint ansible roles/playbooks
        run: ansible-lint ansible/
